# Generated by Django 2.2 on 2022-07-23 19:47

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'Username Sudah Pernah Dipakai.'}, max_length=30)),
                ('email', models.EmailField(error_messages={'unique': 'Email Sudah Pernah Dipakai.'}, max_length=100, unique=True, verbose_name='email')),
                ('user_phone', models.CharField(error_messages={'unique': 'No Hp Sudah Pernah Dipakai.'}, max_length=13)),
                ('user_address', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verif', models.BooleanField(default=False)),
                ('email_verif_code', models.TextField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_hp_verif', models.BooleanField(default=False)),
                ('hp_verif_code', models.TextField()),
                ('verif_exp_time', models.DateTimeField(default=datetime.datetime.now)),
                ('foto', models.TextField(default='')),
                ('token_forgot_pwd', models.TextField(default='')),
                ('forgot_pwd_time_exp', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='created at')),
            ],
            options={
                'unique_together': {('username', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Master_Polling',
            fields=[
                ('polling_id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('polling_question', models.TextField(editable=False, unique=True)),
                ('polling_choices_s', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('polling_allow_multiple', models.BooleanField(default=False)),
                ('polling_comment_off', models.BooleanField(default=False)),
                ('polling_exp_date', models.DateTimeField(default=None, null=True)),
                ('polling_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polling_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
