# Generated by Django 2.2 on 2022-07-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_polling',
            old_name='polling_choices_s',
            new_name='polling_choices',
        ),
    ]
