# Generated by Django 2.2 on 2022-07-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0002_auto_20220724_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_polling',
            name='polling_allow_multiple',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
