# Generated by Django 2.2 on 2022-07-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0003_auto_20220724_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_polling',
            name='polling_allow_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
